"""Pterodactyl Client API wrapper: power actions and a live console/chat
websocket.

Auth uses a Client API key (looks like `ptlc_...`), generated by the user
under Account > API Credentials, scoped to the server they administer.

Game-agnostic -- this only talks to the Pterodactyl panel, never the game
server directly.
"""

from __future__ import annotations

import json
import threading
from collections.abc import Callable
from dataclasses import dataclass

import requests
import websocket

PowerAction = str  # "start" | "stop" | "restart" | "kill"


class PterodactylError(RuntimeError):
    pass


@dataclass
class BackupEntry:
    uuid: str
    name: str
    bytes: int
    is_successful: bool
    is_locked: bool
    created_at: str
    completed_at: str | None


def _parse_backup(attrs: dict) -> BackupEntry:
    return BackupEntry(
        uuid=attrs["uuid"],
        name=attrs.get("name") or attrs["uuid"],
        bytes=attrs.get("bytes") or 0,
        is_successful=bool(attrs.get("is_successful")),
        is_locked=bool(attrs.get("is_locked")),
        created_at=attrs.get("created_at") or "",
        completed_at=attrs.get("completed_at"),
    )


class PterodactylClient:
    def __init__(self, base_url: str, api_key: str, server_id: str):
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key
        self.server_id = server_id
        self._session = requests.Session()
        self._session.headers.update(
            {
                "Authorization": f"Bearer {api_key}",
                "Accept": "application/json",
                "Content-Type": "application/json",
            }
        )

    # -- REST -------------------------------------------------------------------

    def _client_url(self, path: str) -> str:
        return f"{self.base_url}/api/client/servers/{self.server_id}{path}"

    def send_power_action(self, action: PowerAction) -> None:
        if action not in ("start", "stop", "restart", "kill"):
            raise ValueError(f"Unknown power action: {action}")
        resp = self._session.post(self._client_url("/power"), json={"signal": action}, timeout=15)
        if resp.status_code >= 400:
            raise PterodactylError(f"Power action '{action}' failed: {resp.status_code} {resp.text}")

    def send_command(self, command: str) -> None:
        resp = self._session.post(self._client_url("/command"), json={"command": command}, timeout=15)
        if resp.status_code >= 400:
            raise PterodactylError(f"Send command failed: {resp.status_code} {resp.text}")

    def get_current_state(self) -> str:
        """Polled REST ground truth for power state ("starting" / "running" /
        "stopping" / "offline"), independent of the console websocket -- that
        stream has no reconnect logic (see ConsoleStream below), so anything
        that needs to reliably know "is it actually offline yet" (e.g. the
        Backup tab's stop-then-copy flow) should poll this instead of trusting
        a cached status that silently stops updating if the socket drops.
        """
        resp = self._session.get(self._client_url("/resources"), timeout=15)
        if resp.status_code >= 400:
            raise PterodactylError(f"Get server state failed: {resp.status_code} {resp.text}")
        return resp.json()["attributes"]["current_state"]

    # -- file manager (server-side, no data through this process) ---------------
    #
    # Confirmed live against a real node: files/copy returns a 500
    # DaemonConnectionException here (broken/unsupported on this Wings
    # version, unrelated to server load -- fails identically idle or busy),
    # but compress/decompress/rename/delete all work. That combination is
    # exactly what a duplicate-without-streaming-every-file backup needs:
    # compress the save into an archive (Wings does this locally, no network
    # round trip per file), rename the archive into place, and reverse it for
    # restore. Confirmed live that rename works with a nested "from" or "to"
    # path (moving into or out of a subdirectory), not just same-directory
    # renames, and that files/delete removes both files and directories.
    # Falls back to SftpClient.copy_dir/delete_dir (see main_window.py) when
    # there's no Pterodactyl connection to do this with instead.

    def compress_files(self, root: str, files: list[str]) -> dict:
        """Archives `files` (relative to `root`) into a single .tar.gz created
        alongside them in `root`, entirely server-side. Returns the new
        archive's attributes dict (at least "name" and "size")."""
        resp = self._session.post(self._client_url("/files/compress"), json={"root": root, "files": files}, timeout=300)
        if resp.status_code >= 400:
            raise PterodactylError(f"Compress failed: {resp.status_code} {resp.text}")
        return resp.json()["attributes"]

    def decompress_file(self, root: str, file: str) -> None:
        """Extracts an archive in place -- its contents land in `root` using
        whatever top-level name(s) were originally archived."""
        resp = self._session.post(self._client_url("/files/decompress"), json={"root": root, "file": file}, timeout=300)
        if resp.status_code >= 400:
            raise PterodactylError(f"Decompress failed: {resp.status_code} {resp.text}")

    def rename_file(self, root: str, from_path: str, to_path: str) -> None:
        """Metadata-only move/rename -- instant regardless of size, since it's
        the same underlying rename() syscall as `mv` on the same filesystem.
        `from_path`/`to_path` are relative to `root` and may include a `/` to
        move into or out of a subdirectory."""
        resp = self._session.put(
            self._client_url("/files/rename"),
            json={"root": root, "files": [{"from": from_path, "to": to_path}]},
            timeout=30,
        )
        if resp.status_code >= 400:
            raise PterodactylError(f"Rename failed: {resp.status_code} {resp.text}")

    def delete_files(self, root: str, names: list[str]) -> None:
        """Deletes files and/or directories (recursively) server-side."""
        resp = self._session.post(self._client_url("/files/delete"), json={"root": root, "files": names}, timeout=60)
        if resp.status_code >= 400:
            raise PterodactylError(f"Delete failed: {resp.status_code} {resp.text}")

    def list_backups(self) -> list[BackupEntry]:
        resp = self._session.get(self._client_url("/backups"), timeout=15)
        if resp.status_code >= 400:
            raise PterodactylError(f"List backups failed: {resp.status_code} {resp.text}")
        return [_parse_backup(item["attributes"]) for item in resp.json().get("data", [])]

    def create_backup(self) -> BackupEntry:
        resp = self._session.post(self._client_url("/backups"), json={}, timeout=30)
        if resp.status_code >= 400:
            raise PterodactylError(f"Create backup failed: {resp.status_code} {resp.text}")
        return _parse_backup(resp.json()["attributes"])

    def delete_backup(self, backup_uuid: str) -> None:
        resp = self._session.delete(self._client_url(f"/backups/{backup_uuid}"), timeout=15)
        if resp.status_code >= 400:
            raise PterodactylError(f"Delete backup failed: {resp.status_code} {resp.text}")

    def restore_backup(self, backup_uuid: str) -> None:
        resp = self._session.post(
            self._client_url(f"/backups/{backup_uuid}/restore"),
            json={"truncate": True},
            timeout=30,
        )
        if resp.status_code >= 400:
            raise PterodactylError(f"Restore backup failed: {resp.status_code} {resp.text}")

    def _websocket_credentials(self) -> tuple[str, str]:
        resp = self._session.get(self._client_url("/websocket"), timeout=15)
        if resp.status_code >= 400:
            raise PterodactylError(f"Could not get websocket token: {resp.status_code} {resp.text}")
        data = resp.json()["data"]
        return data["socket"], data["token"]


# -- websocket console/chat stream ----------------------------------------------


class ConsoleStream:
    """Background websocket connection streaming console output (incl. chat).

    `on_line(text)` is called for each console output line, `on_status(status)`
    for power/state updates, both from a background thread -- marshal to the
    UI thread before touching widgets.
    """

    def __init__(
        self,
        client: PterodactylClient,
        on_line: Callable[[str], None],
        on_status: Callable[[str], None] | None = None,
    ):
        self._client = client
        self._on_line = on_line
        self._on_status = on_status
        self._ws: websocket.WebSocketApp | None = None
        self._thread: threading.Thread | None = None

    def start(self) -> None:
        socket_url, token = self._client._websocket_credentials()

        def on_open(ws):
            ws.send(json.dumps({"event": "auth", "args": [token]}))

        def on_message(ws, message):
            try:
                payload = json.loads(message)
            except json.JSONDecodeError:
                return
            event = payload.get("event")
            args = payload.get("args") or []
            if event == "console output" and args:
                self._on_line(args[0])
            elif event == "status" and args and self._on_status:
                self._on_status(args[0])
            elif event == "token expiring":
                self._refresh_token(ws)

        def on_error(ws, error):
            self._on_line(f"[connection error: {error}]")

        self._ws = websocket.WebSocketApp(
            socket_url,
            on_open=on_open,
            on_message=on_message,
            on_error=on_error,
        )
        self._thread = threading.Thread(
            target=self._ws.run_forever,
            kwargs={"origin": self._client.base_url},
            daemon=True,
        )
        self._thread.start()

    def _refresh_token(self, ws) -> None:
        try:
            _, token = self._client._websocket_credentials()
            ws.send(json.dumps({"event": "auth", "args": [token]}))
        except PterodactylError:
            pass

    def send_command(self, command: str) -> None:
        if self._ws is None:
            raise PterodactylError("Console stream not started")
        self._ws.send(json.dumps({"event": "send command", "args": [command]}))

    def stop(self) -> None:
        if self._ws is not None:
            self._ws.close()
            self._ws = None
